language: node_js
node_js: 10.15.0
cache: npm

install:
  - npm i

script:
  - npm run lint
  - npm run test:cov
  - npm run build

deploy:
  provider: surge
  project: ./dist/
  domain: rmosaic.surge.sh