
export default {
	FETCH_USER: 'FETCH_USER',
	FETCH_USERS: 'FETCH_USERS',
	FETCH_USER_REPOS: 'FETCH_USER_REPOS',
	ITEM_TOGGLE: 'ITEM_TOGGLE',
	SELECT_ALL: 'SELECT_ALL',
	UPDATE_REPOS: 'UPDATE_REPOS',
	FILTER_REPOS: 'FILTER_REPOS',
	DELETE_REPO: 'DELETE_REPO',
};
