# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update TUI versions

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Every Monday at 1PM UTC (9AM EST)
    # the last * - is day of the week (0 - 6 or SUN-SAT) text
    - cron:  '5,10,15 8-11 * * 2'

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Make changes to pull request
        run: date +%s > report.txt

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: "feat: update report and use cron"
          committer: GitHub <inna-i@github.com>
          # author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: tui-patches
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: inna-i
          reviewers: inna-i
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"



# git checkout -b feat-new-branch
# date > generated.txt
# git config user.name github-actions
# git config user.email github-actions@github.com
# git add .
# git commit -m "feat: generated file"
# git push origin feat-new-branch

